mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    url: jdbc:mysql://rm-wz9v6ey1y446me9055o.mysql.rds.aliyuncs.com/movie?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "@qwe123456"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-module
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
